
module top; 
    import uvm_pkg::*; `include "uvm_macros.svh" 
    timeunit 1ns;     timeprecision 100ps;    
    bit clk,req, ack;  
    int req_count, gnt_count; 
    default clocking @(posedge clk); 
    endclocking
    initial forever #10 clk=!clk;  
    
    always @(posedge clk)  if($rose(req)) 
        req_count  = req_count  + 1'b1;  
    
    always @(posedge clk)  if(ack) 
        gnt_count  = gnt_count  + 1'b1;  

    property reqack_unique;
        int v_serving_req_count ;
        @(posedge clk) ($rose(req),  v_serving_req_count =req_count) |-> 
             (##[1:10] gnt_count ==v_serving_req_count ) ##0 ack; 
    endproperty
    ap_reqack_unique: assert property(reqack_unique); 
    
    
    initial begin 
        repeat(100) begin 
            @(posedge clk); #1;  
            if (!randomize(req, ack)  with 
            { req dist {1'b1:=1, 1'b0:=3};
            ack dist {1'b1:=1, 1'b0:=5};       
        }) `uvm_error("MYERR", "This is a randomize error")
    end 
    repeat(200) begin
        @(posedge clk); #1
        if (!randomize(req, ack)  with 
        { req dist {1'b1:=1, 1'b0:=3};
        ack dist {1'b1:=0, 1'b0:=1};       
    }) `uvm_error("MYERR", "This is a randomize error")
end
$stop; 
end 
endmodule   

// ------------------
// Generated by perplexity 
// will it work in Formal verification? 
// My question! 
module req_gnt_protocol (
  input logic clk,
  input logic rst_n,
  input logic req,
  input logic gnt
);
  
  // Support logic to track requests and grants
  logic [7:0] req_count = 0;
  logic [7:0] gnt_count = 0;
  
  // Track request and grant counts
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      req_count <= 0;
      gnt_count <= 0;
    end
    else begin
      if ($rose(req)) req_count <= req_count + 1;
      if ($rose(gnt)) gnt_count <= gnt_count + 1;
    end
  end
  
  // Properties for formal verification
  
  // 1. No grant without a request
  property p_no_gnt_without_req;
    @(posedge clk) disable iff(!rst_n)
    gnt_count <= req_count;
  endproperty
  
  // 2. Each request must eventually receive a grant
  property p_req_eventually_gnt;
    @(posedge clk) disable iff(!rst_n)
    $rose(req) |-> ##[1:$] $rose(gnt);
  endproperty
  
  // 3. Ensure one-to-one correspondence
  property p_one_to_one_correspondence;
    logic [7:0] req_id;
    @(posedge clk) disable iff(!rst_n)
    ($rose(req), req_id = req_count) |-> 
      ##[1:$] ($rose(gnt) && (gnt_count == req_id + 1));
  endproperty
  
  // 4. Using sequence intersection to ensure uniqueness
  property p_req_gnt_uniqueness;
    logic [7:0] num;
    @(posedge clk) disable iff(!rst_n)
    ($rose(req), num = req_count) |-> 
      // No new request with same ID before grant with this ID
      (##1 !(req && (req_count == num))[*1:$]) 
      intersect
      // Eventually see a grant with this ID
      (##[1:$] $rose(gnt) && (gnt_count == num + 1));
  endproperty
  
  // Assertions for formal verification
  assert property(p_no_gnt_without_req) 
    else $error("Grant without request detected");
    
  assert property(p_req_eventually_gnt) 
    else $error("Request without corresponding grant");
    
  assert property(p_one_to_one_correspondence) 
    else $error("One-to-one correspondence violated");
    
  assert property(p_req_gnt_uniqueness)
    else $error("Request-grant uniqueness violated");
  
  // Cover properties to verify interesting scenarios
  cover property(@(posedge clk) $rose(req) ##[1:5] $rose(gnt));
  cover property(@(posedge clk) req_count - gnt_count == 3); // 3 outstanding requests
  
endmodule

module req_gnt_protocol_with_ids (
  input logic clk,
  input logic rst_n,
  input logic req,
  input logic gnt);
  let MAX_OUTSTANDING = 10;
  
  // Track active requests using a bitmap
  logic [MAX_OUTSTANDING-1:0] req_active = 0;
  logic [7:0] req_counter = 0;
  logic [7:0] gnt_counter = 0;
  
  // Record new requests
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      req_counter <= 0;
      req_active <= 0;
    end
    else if ($rose(req)) begin
      req_active[req_counter % MAX_OUTSTANDING] <= 1'b1;
      req_counter <= req_counter + 1'b1;
    end
  end
  
  // Record grants
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      gnt_counter <= 0;
    end
    else if ($rose(gnt)) begin
      req_active[gnt_counter % MAX_OUTSTANDING] <= 1'b0;
      gnt_counter <= gnt_counter + 1'b1;
    end
  end
  
  // Formal properties
  property p_one_to_one_correspondence;
    @(posedge clk) disable iff(!rst_n)
    $rose(gnt) |-> req_active[gnt_counter % MAX_OUTSTANDING];
  endproperty
  
  assert property(p_one_to_one_correspondence) 
    else $error("Grant without active request");
    
  // Additional properties can be added similar to the first implementation
endmodule
/* Key Verification Points
The support logic uses counters to track requests and grants.
SVA properties verify that:
No grant occurs without a corresponding request.
Each request eventually receives a grant.
The one-to-one correspondence is maintained by ensuring the sequence of grants matches the sequence of requests.
Using sequence intersection ensures that grants are uniquely paired with requests.
Cover properties verify that the protocol can handle multiple outstanding requests and grants within reasonable timing.
These formal verification techniques ensure that the request-grant protocol maintains a strict one-to-one correspondence, 
which is essential for correct system operation

*/
